### ISSUE TITLE
引入serivces.jar报错

### ISSUE THREAD

**Issue by qq6r** [Reginer/aosp-android-jar#10]
项目中进入api-31的services.jar放到libs下,build.gradle中加入compileOnly files('libs/service-api-31.jar'),编译时报错
com.android.tools.r8.internal.Jc: Absent Code attribute in method that is not native or abstract
请帮忙看看是哪里的问题

**Comment by Reginer** [comment]
`service-api-31.jar` 的主要作用是用来看的，当然它也支持引入编译。大多数情况下它被使用的场景比较少，所以实际情况我并没有mock处理和整体引入。

但是你可以这样使用，将你需要使用的某些类，从`services.jar`中移动到`android.jar`中，只用`android.jar`参与编译。移动方式是使用压缩软件打开jar包，直接用鼠标拖到相应路径就可以。

至于如何mock，或者屏蔽jar包验证，可以参照 https://github.com/Reginer/MockableJarGenerator

**Comment by qq6r** [comment]
好的,了解了
