### ISSUE TITLE
请教一下service.jar这个文件是做什么的?怎么用?

### ISSUE THREAD

**Issue by Likeyong** [Reginer/aosp-android-jar#13]
能遇到这么项目真是太幸运了,我可以不用下载源码再去编译,只用替换一下jar包就能查看很多源码,android.jar简直就是一个活宝,和他同一目录的service.jar我想肯定也不会差到哪去,所以想请教一下service.jar这个文件我该怎么使用他.万分感谢~~~

**Comment by Reginer** [comment]
差别很大。

`android.jar`作为`frameworks`的`api`来用，用来编译`apk`，这就是原生`SDK`的概念。

而`service.jar`作为系统的运行时，可以用来做`hook`替换，使编译更容易。

`service.jar`更多的功能是用来看的(比如用jadx，也就是说没用)，等到对系统有一定了解或者有了一定权限之后，使用的方式是把`service.jar`对应的类直接移到`android.jar`的对应目录下，参与编译。

很多的使用场景是`hook`原生`service`，比如`PKMS`，`AMS`等等
