### ISSUE TITLE
Hello，我自行添加了一些文件到 Android.jar里面之后报了这个错误请问下有没有遇到过呢？Could not resolve all files for configuration ':app:androidApis'. 

### ISSUE THREAD

**Issue by MrR0990** [Reginer/aosp-android-jar#15]
> Could not resolve all files for configuration ':app:androidApis'.
   > Failed to transform android.jar to match attributes {artifactType=android-mockable-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime, returnDefaultValues=false}.
      > Execution failed for MockableJarTransform: /Users/tomorrow/Library/Android/sdk/platforms/android-32/android.jar.
         > Cannot read field "outgoingEdges" because "handlerRangeBlock" is null

**Comment by Reginer** [comment]
你自己进行的操作遇到问题先自己解决

**Comment by Reginer** [comment]
https://blog.csdn.net/qq_26413249/article/details/109819624
