### ISSUE TITLE
求更新34的

### ISSUE THREAD

**Issue by ucxl** [Reginer/aosp-android-jar#17]
求大佬更新sdk34的

**Comment by Reginer** [comment]
34的源码还没出



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月15日(周二) 晚上9:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Reginer/aosp-android-jar] 求更新34的 (Issue #17)




 
求大佬更新sdk34的
