### ISSUE TITLE
jar包里缺少文件可以提issue，新开issue

### ISSUE THREAD

**Issue by Reginer** [Reginer/aosp-android-jar#2]

**Comment by fripSide** [comment]
Android-API 29和30的jar里面的hide-api的method都是空的，例如：android.app.Notification，是因为提取的时候特意用的不带方法体只带方法签名的classes-header.jar？
虽然不影响AndroidStudio里面使用，但是想拿来做静态分析就需要有源码的jar。没时间去编译源码了，我从模拟器提取看看。

**Comment by Reginer** [comment]
这种的直接看对应的类的源码就好了，hide方法都是用来编译用的。

**Comment by CCint3** [comment]
可以讲一下制作方式吗？我想适配一下aosp 8.1.0

**Comment by Reginer** [comment]
> 可以讲一下制作方式吗？我想适配一下aosp 8.1.0

https://blog.csdn.net/qq_26413249/article/details/78934458

**Comment by MrR0990** [comment]
Android 13 会适配吗?

**Comment by Reginer** [comment]
> Android 13 会适配吗?

源码没出，出了就适配

**Comment by AlanFeng20** [comment]
services.jar是什么，需要放在哪里吗

**Comment by Reginer** [comment]
> services.jar是什么，需要放在哪里吗

看源码用的，编译用不到，不需要放哪

**Comment by sh1018727638** [comment]
缺少android. os. SystemProperties. java
api33

**Comment by Reginer** [comment]
> 缺少android. os. SystemProperties. java api33

实际上有，不要在这里回了，已经写了新开issue 。jar包里有的是class。

**Comment by neu233** [comment]
可以添加一个android-stubs-src.jar吗
