### ISSUE TITLE
引用api34报错的情况

### ISSUE THREAD

**Issue by ucxl** [Reginer/aosp-android-jar#20]
感谢大神编译34的api，我把这个jar替换到api目录里同步后发现一些报错如下
  错误的类文件: D:\sdk\platforms\android-34\android.jar(/android/os/Parcel.class)
    类文件具有错误的版本 61.0, 应为 55.0
    请删除该文件或确保该文件位于正确的类路径子目录中。
D:\SoulTweaks\app\src\main\java\android\dolby\DsClientSettings.java:4: 错误: 无法访问Parcelable
import android.os.Parcelable;
                 ^
  错误的类文件: D:\sdk\platforms\android-34\android.jar(/android/os/Parcelable.class)
    类文件具有错误的版本 61.0, 应为 55.0
    请删除该文件或确保该文件位于正确的类路径子目录中。

类似的还有很多

**Comment by Reginer** [comment]
把你的AS或者Java升级一下，比如使用最新版本AS，jdk17

**Comment by ucxl** [comment]
感谢大大

**Comment by Reginer** [comment]
https://blog.51cto.com/u_16175449/6796976  
参照这个看一下，可能是jdk的问题
使用下面配置试一下，不行再升级AS
```
compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
```
