### ISSUE TITLE
34的jar无法直接调用ConnectivityManager.setAirplaneMode()

### ISSUE THREAD

**Issue by sh1018727638** [Reginer/aosp-android-jar#25]
之前33，32都是可以调用到的，34直接找不到这个函数，但是打开源码还是可以看到这个api是有的，是34做了什么限制吗
![Uploading 2024-03-20_11.19.13.jpg…]()

**Comment by sh1018727638** [comment]
![2024-03-20_11 20 32](https://github.com/Reginer/aosp-android-jar/assets/18133575/519399ae-2b72-4e7e-a87d-7ddf86b68cff)
34的ConnectivityManager里面找到的，就是形式和33的不同，这里的可以看到全部的逻辑，而33里面是{ compile code }

**Comment by Reginer** [comment]
实际测试可以
![image](https://github.com/Reginer/aosp-android-jar/assets/12568257/5574faf5-32f2-4de9-8940-cfe3cd8dd980)

同时 https://github.com/Reginer/aosp-android-jar/tree/main/android-34 这下面对应android.jar里也是有对应方法的。
![image](https://github.com/Reginer/aosp-android-jar/assets/12568257/16f8e013-9f63-4131-8ff4-c27bd724191d)

**Comment by Reginer** [comment]
你看是否是你使用的android.jar不是 https://github.com/Reginer/aosp-android-jar/tree/main/android-34 里的，重新替换之后sync一下看看

**Comment by sh1018727638** [comment]
应该是替换错误了，重新替换了一下OK了，多谢
