### ISSUE TITLE
Could not resolve all files for configuration ':app:androidApis'. Unsupported class file major version 61

### ISSUE THREAD

**Issue by tumatanquang** [Reginer/aosp-android-jar#29]
Hello, I followed the android.jar file replacement guide. However, when I change the Build Variants or build.gradle and have to re-sync the project afterwards, I get the error:

```
Could not resolve all files for configuration ':app:androidApis'.
Failed to transform android.jar to match attributes {artifactType=android-mockable-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime, returnDefaultValues=false}.
Execution failed for MockableJarTransform: C:\ProgramData\Sdk\platforms\android-34\android.jar.
Unsupported class file major version 61
```

After that, I tried updating java from JDK-11 to JDK-17 and tried to clean it up then rebuild the project, at this point, only the error `Unsupported class file major version 61` appeared.

I tried Invalidate Caches/Restart but still didn't fix the above error.

My Android Studio Info:

- Android Studio Arctic Fox (2020.3.1 Patch 4)
- Android Gradle Plugin Version: 7.0.4
- Gradle Version: 7.0.2

**Comment by Reginer** [comment]
需要使用较新的AS，比如Android Studio Koala | 2024.1.1，或者比这旧一点的。
jdk选择AS自带的jbr
