### ISSUE TITLE
如何从AOSP源码获取这个src 目录下的东西

### ISSUE THREAD

**Issue by ve3344** [Reginer/aosp-android-jar#34]
framework 代码在AOSP源码中不在同一个目录。
需要怎么知道具体在哪些目录呢。也就是这个src的内容是一个个找的还是通过什么方式获取？

**Comment by Reginer** [comment]
我不知道有什么方式可以一下获取全部，我是一个个找的。
也许没有，毕竟谷歌官方给的SDK源码都不全。

**Comment by ve3344** [comment]
好的，感谢
