### ISSUE TITLE
添加android-stubs-src.jar

### ISSUE THREAD

**Issue by neu233** [Reginer/aosp-android-jar#36]
能否添加一个android-stubs-src.jar

**Comment by Reginer** [comment]
这个jar是做什么用的，里面有什么内容

**Comment by neu233** [comment]
> 这个jar是做什么用的，里面有什么内容

都是这种代码
`throw new RuntimeException("Stub!");`

方法内是没有具体实现的代码的，我软件想远程下载java进行编译，但是完整的android.jar又太大了

**Comment by Reginer** [comment]
使用 https://github.com/Reginer/aosp-android-jar/tree/main/android-35/android.jar   不就好了

**Comment by neu233** [comment]
> 使用https://github.com/Reginer/aosp-android-jar/tree/main/android-35/android.jar 不就好了

但是好大

**Comment by Reginer** [comment]
在原生android.jar上增加了隐藏api肯定要比原生的大很多，你要的那个android-stubs-src.jar我不会编辑

**Comment by neu233** [comment]
> 在最近android.jar上增加了隐藏api肯定相当的很多，你要那个android-stubs-src.jar我不会编辑

好吧，那我自己看看能不能用dexlib2生成一个吧

**Comment by Reginer** [comment]
如果你知道怎么能生成出来，我可以生成之后上传

**Comment by neu233** [comment]
> 如果你知道怎么能生成出来，我可以生成之后上传

好的

**Comment by neu233** [comment]
> 如果你知道怎么能生成出来，我可以生成之后上传

找到了一个插件可以一键生成stubs的
https://github.com/tylerbwong/metalava-gradle

**Comment by Reginer** [comment]
这种AS插件用不了。
我发的android.jar实际就已经是这种的了，只有方法声明没有方法体，你用jadx打开就能看到。
只不过api太多所以很大，小说明方法不全，如果你只想用其中几个，你可以从android.jar中把class文件解压出来重新生成一个只有你需要的

**Comment by neu233** [comment]
> 这种AS插件用不了。 我发的android.jar其实就已经是这种了，只有方法声明没有方法体，你用jadx打开就能看到。 只是api太多所以很大，小说明方法不全，如果你要用其中几个，你可以从android.jar中把class文件解压出来重新生成一个只有你需要的

真的是。我的锅，没注意看。
