### ISSUE TITLE
请问为什么EthernetManager.getConfiguration这个方法无法调用呢？

### ISSUE THREAD

**Issue by KittenBall** [Reginer/aosp-android-jar#37]
如题
![image](https://github.com/user-attachments/assets/a1b7e4be-e4a3-4135-ae0b-0df47f9fe444)

我是直接替换的AndroidStudio的sdk目录下platform-34的anroid.jar

EthernetManager可以访问到，但这个方法调用不到

不太了解这方面的知识，不好意思。

**Comment by Reginer** [comment]
[connectivity.zip](https://github.com/user-attachments/files/17129112/connectivity.zip)
因为我上传的34里面的android.jar里面没有这个方法。
可以将我上面传的压缩包文件，直接拖到34的android.jar里面，之后sync项目就可以了。
我现在没有验证，之后会合并上传

**Comment by Reginer** [comment]
不会合并也可以去着重新下载
https://github.com/Reginer/aosp-android-jar/tree/main/android-34

**Comment by KittenBall** [comment]
能麻烦您将android-35也添加一下吗？当然我还没测试，如果已经添加了，就当我多问了。
再次感谢

**Comment by KittenBall** [comment]
楼主，#40  修复后，这个问题又出现了，android 34.
麻烦看看，谢谢

**Comment by Reginer** [comment]
上传了

**Comment by KittenBall** [comment]
好了，谢谢
