### ISSUE TITLE
NFC enable/disable, Android 14 - exception

### ISSUE THREAD

**Issue by henrichg** [Reginer/aosp-android-jar#38]
My application calls (compileSdkVersion 35) INfcAdapter.enable(), INfcAdapter.disable().
Android Studio asks for a parameter packageName.

```
INfcAdapter adapter = INfcAdapter.Stub.asInterface(ServiceManager.getService("nfc"));
return enable ? adapter.enable(PPApplication.PACKAGE_NAME) : adapter.disable(true, PPApplication.PACKAGE_NAME);
```
But call of this code generates exceptions in Android 14:

adapter.disable(true, PPApplication.PACKAGE_NAME)
java.lang.NoSuchMethodError: No interface method disable(ZLjava/lang/String;)Z in class Landroid/nfc/INfcAdapter; or its super classes (declaration of 'android.nfc.INfcAdapter' appears in /system/framework/framework.jar!classes3.dex)
at sk.henrichg.phoneprofilesplus.CmdNfc.setNFC(CmdNfc.java:27)

adapter.enable(PPApplication.PACKAGE_NAME):
java.lang.NoSuchMethodError: No interface method enable(Ljava/lang/String;)Z in class Landroid/nfc/INfcAdapter; or its super classes (declaration of 'android.nfc.INfcAdapter' appears in /system/framework/framework.jar!classes3.dex)
at sk.henrichg.phoneprofilesplus.CmdNfc.setNFC(CmdNfc.java:27)

---

With compileSdkVersion 34 working this (without packageName as parameter):

```
INfcAdapter adapter = INfcAdapter.Stub.asInterface(ServiceManager.getService("nfc"));
return enable ? adapter.enable() : adapter.disable(true);
```

But this not working in Android 15 (Pixel 6).

---

Is bug in INfcAdapter? Please check it.

**Comment by Reginer** [comment]
安卓14和安卓15代码中的`INfcAdapter.aidl`文件是有区别的，包括`enable`和`disable`方法增加了`pkg`参数。
[安卓15INfcAdapter.aidl](https://cs.android.com/android/platform/superproject/+/android-15.0.0_r1:frameworks/base/nfc/java/android/nfc/INfcAdapter.aidl;drc=c4502aa2b8764601d2a0715c5650bbb724a479c1;l=53)
[安卓14INfcAdapter.aidl](https://cs.android.com/android/platform/superproject/+/android14-qpr3-release:frameworks/base/nfc/java/android/nfc/INfcAdapter.aidl;drc=ee03676afffd44da6dd718c4f602d8a4190a2b2a;l=51)

遇到这种同方法参数不同或者返回值不同的问题，我推荐在最新版本上直接调用，而适配旧版本采用反射。
例如 :
```
        INfcAdapter adapter = INfcAdapter.Stub.asInterface(ServiceManager.getService("nfc"));
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.VANILLA_ICE_CREAM) {
            return enable ? adapter.enable(PPApplication.PACKAGE_NAME) : adapter.disable(true, PPApplication.PACKAGE_NAME);
        } else {
            return enable ? ReflectUtils.reflect(adapter).method("enable").get() : ReflectUtils.reflect(adapter).method("disable", true).get();
        }
```

**Comment by henrichg** [comment]
Please ReflectUtils is which package? Android Studio doesn't know it.
Thanks.

**Comment by Reginer** [comment]
是一个反射工具类，源码在
https://github.com/Blankj/AndroidUtilCode/blob/master/lib/utilcode/src/main/java/com/blankj/utilcode/util/ReflectUtils.java

**Comment by henrichg** [comment]
Working! :-)
Thank you very much.

**Comment by henrichg** [comment]
.
