### ISSUE TITLE
Execution failed for MockableJarTransform: /Users/tomorrow/Library/Android/sdk/platforms/android-31/android.jar. Transform output android.jar must exist.

### ISSUE THREAD

**Issue by MrR0990** [Reginer/aosp-android-jar#39]
![image](https://github.com/user-attachments/assets/4fc1239d-2dd1-49bf-b55c-a55f76048aaa)

升级了Gradle8.6.0之后,清空 MockableJarGenerator 中的 createMockableJar() 方法体,发现报了如图红框中的提示Transform output android.jar must exist.

这个问题有遇到过吗? 记得以前是没有 ransform output android.jar must exist. 这句的

**Comment by Reginer** [comment]
你是如何复现的，使用我的jar不需要修改其他任何内容，只需要把我上传的jar文件替代原生的android.jar

**Comment by MrR0990** [comment]
原理gradle 7.0.3 按照 https://blog.csdn.net/qq_26413249/article/details/109819624?spm=1001.2014.3001.5502 修改之后一直可以用

最进需要升级gradle 

把Android 34 原来的Android.jar 替换成你的Android.jar就出现这个问题了,

然后我在尝试使用你的帖子的方法修改 https://blog.csdn.net/qq_26413249/article/details/109819624?spm=1001.2014.3001.5502

**Comment by Reginer** [comment]
使用我提供的android.jar,你不要修改gradle的源码，先把你修改的删除，使用官方原生的gradle。
然后如果你想使用android34的jar包，只需要把android-34下的jar替换到原生sdk目录下同名文件。
最后将项目的compileSdk改为34。
贴子上的操作是想要自己增加其他代码，不用我提供的android.jar才去修改gradle源码 。

**Comment by MrR0990** [comment]
感谢,在替换的过程中不能开着AS ,我重启下电脑就可以了
