### ISSUE TITLE
Android-32应该是Android13版本吧?没明白为什么编译的分支是Android12的android-12.1.0_r5分支编译,能帮忙解答下吗?

### ISSUE THREAD

**Issue by MrR0990** [Reginer/aosp-android-jar#4]
Android-32应该是Android13版本吧?
没明白为什么编译的分支是Android12的android-12.1.0_r5分支编译,能帮忙解答下吗?

我的理解应该是采用android13对应的分支编译才对吧

**Comment by Reginer** [comment]
Android-32 是 12.1  ， 在`Build.java`里是`S_V2`
![image](https://user-images.githubusercontent.com/12568257/167986287-7fc5e912-ee88-4eb6-a2e5-1190f75a9a65.png)

**Comment by MrR0990** [comment]
明白了,谢谢
