### ISSUE TITLE
请问可以添加WifiManager的隐藏函数吗

### ISSUE THREAD

**Issue by KittenBall** [Reginer/aosp-android-jar#40]
现在startSoftAp调用不到

谢谢楼主

需求android14，android15

**Comment by KittenBall** [comment]
实际上是有的，源码里能看到，现象和#37一样呀

**Comment by Reginer** [comment]
android-34和android-35里面是有的

**Comment by KittenBall** [comment]
![image](https://github.com/user-attachments/assets/41d158f5-afc2-4989-b128-e5a28de1135a)
我也不知道为啥，setWifiApConfiguration也是系统api，就能调用到，但是startSoftAp不行。

**Comment by Reginer** [comment]
![image](https://github.com/user-attachments/assets/95768ea8-9e32-4700-844e-99ed0aa6a7bc)
截图内容是android-35内的。把compileSdk改成35。
你怕不是今天早上更新了35的jar包，把我35的jar包替换回去

**Comment by KittenBall** [comment]
我的compileSdk是34，目前不好改35，那样要改的东西太多了
然后用的是34的sdk

**Comment by Reginer** [comment]
你重新下载一下看看
https://github.com/Reginer/aosp-android-jar/tree/main/android-34

**Comment by KittenBall** [comment]
好了，谢谢
