### ISSUE TITLE
请问一下如何编译出android.jar

### ISSUE THREAD

**Issue by chen849343227** [Reginer/aosp-android-jar#6]
请问怎么在源码里面编译出这个android.jar呀，还有这个android.jar包含资源文件不？

**Comment by Reginer** [comment]
简单给你说下流程吧，先现在安卓源码 ，我是从  https://mirrors.tuna.tsinghua.edu.cn/help/AOSP/ 下载
下载之后编译

```
 source build/envsetup.sh
 lunch 随便一个
 make -j{$cpu核心数*2}
```
编译之后，将`out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/classes-header.jar`合并到官方提供的Android.jar内，资源文件没有增加，还是原生jar包内的资源文件 。


官方提供的android.kar是通过`make sdk`编译出来的
