### ISSUE TITLE
android-33 里面少这个常量 PowerManager.REBOOT_REQUESTED_BY_DEVICE_OWNER 

### ISSUE THREAD

**Issue by wangbo4020** [Reginer/aosp-android-jar#7]
如题
源码里面有的
[frameworks/base/core/java/android/os/PowerManager.java](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/os/PowerManager.java)

**Comment by Reginer** [comment]
有的 ，类名打错了吧
![image](https://user-images.githubusercontent.com/12568257/191471836-43337be5-63e8-46bf-9aae-b49761d8fcd1.png)

**Comment by Reginer** [comment]
![image](https://user-images.githubusercontent.com/12568257/191472535-79eb6b70-8ef2-478a-a307-40b9dc2102ea.png)

**Comment by wangbo4020** [comment]
噢，是有的，不好意思
