### ISSUE TITLE
缺少 sun.**

### ISSUE THREAD

**Issue by eirv** [Reginer/aosp-android-jar#8]
比如
sun.misc.Unsafe.**
public native long java.lang.reflect.Field.getArtField()
这些可以加上吗？

**Comment by Reginer** [comment]
我看你这包名，怕不是JDK里的吧。
你想用在哪个版本的android.jar里？
如果源码里有的话，我可以(教你)加到最新的jar里面。

**Comment by Reginer** [comment]
[core-all.zip](https://github.com/Reginer/aosp-android-jar/files/9713052/core-all.zip)

我猜测你要的可能是这个东西，解压出来是`core-all.jar`，用压缩软件打开，将你想用的类移动到`android.jar`里面就可以使用了。

[类似这样的操作](https://github.com/Reginer/aosp-android-jar/issues/5) 

https://user-images.githubusercontent.com/12568257/189843481-b6083fb1-8859-4541-a70b-11f484e332cc.mp4
