### ISSUE TITLE
缺少android. os. SystemProperties. java

### ISSUE THREAD

**Issue by sh1018727638** [Reginer/aosp-android-jar#9]
我下载了api33的android. jar，里面没有这个文件，大佬

**Comment by Reginer** [comment]
![image](https://user-images.githubusercontent.com/12568257/196084257-56f2bc41-a3dc-40cb-9142-4f98da85e475.png)

**Comment by Reginer** [comment]
文件下载全了吧，这么大。用压缩软件可以打开 。 
![image](https://user-images.githubusercontent.com/12568257/196084595-8706c178-83cd-4d63-b20e-f3d0b7ba4f85.png)

**Comment by sh1018727638** [comment]
抱歉，jar包里面确实看到了，替换platforms/android33/android. jar
Android studio 重新加载之后看不到这个文件，是被隐藏了吗

**Comment by Reginer** [comment]
AS也可以加载，我现在就用的这个，加载哪个得看compileSdk指定的多少 。

**Comment by Reginer** [comment]
鼠标放到这里右键，把下载的jar包替换到这里。
![image](https://user-images.githubusercontent.com/12568257/196086711-7d388234-34f9-4237-9768-663d7df7c50c.png)

**Comment by sh1018727638** [comment]
对的，我就是compile了33，替换的也是33的android. jar，我试一下清除缓存，重新启动一下

**Comment by sh1018727638** [comment]
对的，我就是compile了33，替换的也是33的android. jar，我试一下清除缓存，重新启动一下

**Comment by Reginer** [comment]
好了没

**Comment by sh1018727638** [comment]
还是只显示旧android. jar的结构，我看到还有一个android-stubs-src. jar，这个文件的结构和android. jar 一致，是否会有关联性

**Comment by sh1018727638** [comment]
我可以确认android. jar已经被替换了，我的做法是吧旧的给删除了，然后把新的放进android-33里面了

**Comment by Reginer** [comment]
加我qq我帮你看一下，282921012
